### ISSUE TITLE
Makes PHP Icons appear as Blackberry icons

### ISSUE THREAD

**Issue by Otterpocket** [aaroncdr/ss-atom#1]
When used in conjunction with the popular file-icons Package (https://atom.io/packages/file-icons)
![image](https://cloud.githubusercontent.com/assets/7274458/10638142/3ea9e7de-7801-11e5-9a1d-f0713a45950e.png)

**Comment by ACDR** [comment]
Hi @Otterpocket, this should be fixed now. :)

**Comment by Otterpocket** [comment]
Awesome :+1:
